export const projects = [
  {
    title: "한강, 2022.9.17 출발",
    description: `A complete design system for a website that can be used for any website with a dark and light theme and a lot of components premade based TailwindCSS.`,
    img: "/re100run/1.png",
    href: "/projects/ecommerce",
    preview: "https://www.ripple-ui.com/",
    github: "https://github.com/Siumauricio/rippleui",
    alt: "Projects",
    platform: "Web",
    stack: "TailwindCSS, Nextjs, Typescript, CSS.",
    delay: 0.1,
  },
  {
    title: "한강, 2022.9.17 출발",
    description: `A complete design system for a website that can be used for any website with a dark and light theme and a lot of components premade based TailwindCSS.`,
    img: "/re100run/2.png",
    href: "/projects/ecommerce",
    preview: "https://www.ripple-ui.com/",
    github: "https://github.com/Siumauricio/rippleui",
    alt: "Projects",
    platform: "Web",
    stack: "TailwindCSS, Nextjs, Typescript, CSS.",
    delay: 0.1,
  },
]